# Generated by Django 4.1.2 on 2022-11-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='typeJob',
            field=models.CharField(default='Nan', max_length=25),
            preserve_default=False,
        ),
    ]
